apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookinfo-dev-ratings
  namespace: bookinfo-service 
  labels:
    app: bookinfo-dev-ratings
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookinfo-dev-ratings
  template:
    metadata:
      labels:
        app: bookinfo-dev-ratings
    spec:
      containers:
      - name: bookinfo-dev-ratings
        image: registry.opsta.in.th/bookinfo/ratings:v1.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: web-port
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
        env:
        # - name: SERVICE_VERSION
        #   value: v1
         - name: SERVICE_VERSION
           value: v2
         - name: MONGO_DB_URL
           value: mongodb://mongodb:27017/ratingsdev
         - name: MONGO_DB_USERNAME
           value: ratingsdev
         - name: MONGO_ROOT_PASSWORD
           value: ratings-dev
      #   - name: MONGO_DB_PASSWORD
       #    valueFrom:
       #     secretKeyRef:
       #       name: bookinfo-dev-ratings-mongodb-secret
       #       key: mongodb-root-password
      imagePullSecrets:
      - name: registry-bookinfo
