ratings:
  namespace: bookinfo-service
  image: registry.opsta.in.th/bookinfo/ratings
  tag: v1.0.1
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8080
  #healthCheckPath: "/health"
  mongodbPasswordExistingSecret: bookinfo-dev-ratings-mongodb-secret  
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: polawich.opsta.in.th
  #path: "/ratings(/|$)(.*)"
  serviceType: ClusterIP
#extraEnv:
#  SERVICE_VERSION: v2
#  MONGO_DB_URL: mongodb://bookinfo-dev-ratings-mongodb:27017/ratings-dev
#  MONGO_DB_USERNAME: ratings-dev
