apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: {{ .Release.Name }}
  namespace: {{ Values.ratings.namespace }}
spec:
  rules:
  - host: {{ Values.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: {{ Release.Name }}
          servicePort: {{ Values.ratings.port }}
        path: "/ratings(/|$)(.*)"