apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.ratings.namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.ratings.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.ratings.image }}:{{ .Values.ratings.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.ratings.port }}
          name: web-port
          protocol: TCP
        livenessProbe:
          httpGet:
            path: "/health"
            port: {{ .Values.ratings.port }}
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: "/health"
            port: {{ .Values.ratings.port }}
            scheme: HTTP
        env:
        - name: SERVICE_VERSION #value v1 no dbs
          value: v2
        - name: MONGO_DB_URL
          value: mongodb://ratingsdev:ratingsdev@mongodb.bookinfo-service:27017/ratings
      imagePullSecrets:
      - name: {{ .Values.ratings.imagePullSecrets }}
       #   value: mongodb://mongodb:27017/ratingsdev
       # - name: MONGO_DB_USERNAME
       #   value: ratingsdev
       # - name: MONGO_DB_PASSWORD
       #   value: ratingsdev
          #valueFrom:
          #  secretKeyRef:
          #    name: bookinfo-dev-ratings-mongodb-secret
          #    key: mongodb-password
